# Written by rothman (2023/01/05)
# * If a player has permissions for multiple chat formats, the format with the highest priority is chosen.
# * The format must contain a placeholder such as %player_name% or %player_displayname% otherwise it will not work.
# * All the text before and after the player name placeholder are the prefix and suffix respectively.
chat-formats:
  default:
    priority: 1
    permission: 'corechat.default'
    chat-color: '&7'
    format: '%luckperms_prefix% %player_displayname% %luckperms_suffix%&8&l»'
    options:
      prefix-click-command: ''
      name-click-command: '/msg %player_name% '
      suffix-click-command: ''
      prefix-hover-message:
        - '&fBalance: &a&o$%vault_eco_balance%'
      name-hover-message:
        - '&fBalance: &a&o$%vault_eco_balance%'
        - '&7Click me to PM!'
      suffix-hover-message: []
  admin:
    priority: 100
    permission: 'corechat.admin'
    chat-color: '&c'
    format: '%luckperms_prefix% %player_displayname% %luckperms_suffix%&8&l»'
    options:
      prefix-click-command: ''
      name-click-command: '/msg %player_name% '
      suffix-click-command: ''
      prefix-hover-message:
        - '&fBalance: &a&o$%vault_eco_balance%'
      name-hover-message:
        - '&fBalance: &a&o$%vault_eco_balance%'
        - '&7Click me to PM!'
      suffix-hover-message: []
