name: CoreChat
version: '${project.version}'
main: me.rothman5.corechat.CoreChat
api: '1.17'
api-version: '1.17'
depend: [ PlaceholderAPI ]
authors: [ rothman5 ]
description: '${project.description}'
commands:
  corechat:
    description: Master command for this plugin.
    aliases: [ 'cc' ]
